name: movies-analysis
services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  requesthandler:
    build:
      context: .
      dockerfile: cmd/requesthandler/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./docs:/docs
    command: /requesthandler/request_handler.go

  receiver:
    build:
      context: .
      dockerfile: cmd/receiver/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy

  filter_2000s_q1:
    environment:
      QUERY: 1
    build:
      context: .
      dockerfile: cmd/filters/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /filter_2000s/filter_2000s.go

  filter_2000s_q4:
    environment:
      QUERY: 4
    build:
      context: .
      dockerfile: cmd/filters/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /filter_2000s/filter_2000s.go

  filter_2000s_q3:
    environment:
      QUERY: 3
    build:
      context: .
      dockerfile: cmd/filters/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /filter_2000s/filter_2000s.go
  ratingsreceiver:
    build:
      context: .
      dockerfile: cmd/ratingsreceiver/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy

  q1_sink:
    build:
      context: .
      dockerfile: cmd/sinks/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /q1_sink/q1_sink.go
  budget_reducer:
    build:
      context: .
      dockerfile: cmd/reducers/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /budget_reducer.go
    deploy:
      replicas: 1

  budget_sink:
    build:
      context: .
      dockerfile: cmd/sinks_q2/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /budget_sink/budget_sink.go

  credits_joiner:
    environment:
      ID: 1
    build:
      context: .
      dockerfile: cmd/joiners_q4/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    

  credits_receiver:
    build:
      context: .
      dockerfile: cmd/credits_receiver/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /credits_receiver/credits_receiver.go

  ratings_joiner:
    environment:
      ID: 1
    build:
      context: .
      dockerfile: cmd/joiners/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy

  q3_sink:
    build:
      context: .
      dockerfile: cmd/sinks_q3/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /q3_sink/q3_sink.go