name: movies-analysis
services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
    healthcheck:
      test:
        - CMD
        - rabbitmqctl
        - status
      interval: 10s
      timeout: 5s
      retries: 5
  requesthandler:
    environment:
      ID: 1
      REPLICAS: 1
    image: movies/requesthandler:latest
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./docs:/docs
    command: /requesthandler/request_handler.go
  moviesreceiver_1:
    image: movies/moviesreceiver:latest
    environment:
      ID: 1
      REPLICAS: 2
    depends_on:
      rabbitmq:
        condition: service_healthy
  moviesreceiver_2:
    image: movies/moviesreceiver:latest
    environment:
      ID: 2
      REPLICAS: 2
    depends_on:
      rabbitmq:
        condition: service_healthy
  filter_q1_1:
    image: movies/filter:latest
    environment:
      ID: 1
      REPLICAS: 2
      QUERY: 1
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /filter/filter.go
  filter_q1_2:
    image: movies/filter:latest
    environment:
      ID: 2
      REPLICAS: 2
      QUERY: 1
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /filter/filter.go
  filter_q3_1:
    image: movies/filter:latest
    environment:
      ID: 1
      REPLICAS: 2
      QUERY: 3
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /filter/filter.go
  filter_q3_2:
    image: movies/filter:latest
    environment:
      ID: 2
      REPLICAS: 2
      QUERY: 3
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /filter/filter.go
  filter_q4_1:
    image: movies/filter:latest
    environment:
      ID: 1
      REPLICAS: 2
      QUERY: 4
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /filter/filter.go
  filter_q4_2:
    image: movies/filter:latest
    environment:
      ID: 2
      REPLICAS: 2
      QUERY: 4
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /filter/filter.go
  ratingsreceiver_1:
    image: movies/ratingsreceiver:latest
    environment:
      ID: 1
      REPLICAS: 2
    depends_on:
      rabbitmq:
        condition: service_healthy
  ratingsreceiver_2:
    image: movies/ratingsreceiver:latest
    environment:
      ID: 2
      REPLICAS: 2
    depends_on:
      rabbitmq:
        condition: service_healthy
  ratingsjoiner_1:
    image: movies/ratingsjoiner:latest
    environment:
      ID: 1
      REPLICAS: 2
    depends_on:
      rabbitmq:
        condition: service_healthy
  ratingsjoiner_2:
    image: movies/ratingsjoiner:latest
    environment:
      ID: 2
      REPLICAS: 2
    depends_on:
      rabbitmq:
        condition: service_healthy
  q1_sink_1:
    image: movies/sink:latest
    environment:
      ID: 1
      REPLICAS: 1
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /q1_sink/q1_sink.go
  q3_sink_1:
    image: movies/sink_q3:latest
    environment:
      ID: 1
      REPLICAS: 1
    depends_on:
      rabbitmq:
        condition: service_healthy
  budget_reducer_1:
    image: movies/reducer:latest
    environment:
      ID: 1
      REPLICAS: 2
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /budget_reducer.go
  budget_reducer_2:
    image: movies/reducer:latest
    environment:
      ID: 2
      REPLICAS: 2
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /budget_reducer.go
  budget_sink_1:
    image: movies/sink_q2:latest
    environment:
      ID: 1
      REPLICAS: 1
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /budget_sink/budget_sink.go
  # sentiment_worker_1:
  #   image: movies/sentiment:latest
  #   environment:
  #     ID: 1
  #     REPLICAS: 2
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # sentiment_worker_2:
  #   image: movies/sentiment:latest
  #   environment:
  #     ID: 2
  #     REPLICAS: 2
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # sentiment_reducer_1:
  #   image: movies/sentiment_reducer:latest
  #   environment:
  #     ID: 1
  #     REPLICAS: 1
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   command: /sentiment_reducer/sentiment_reducer.go
  # sentiment_sink_1:
  #   image: movies/sink_q5:latest
  #   environment:
  #     ID: 1
  #     REPLICAS: 1
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   command: /sentiment_sink/sentiment_sink.go
  credits_joiner_1:
    image: movies/credits_joiner:latest
    environment:
      ID: 1
      REPLICAS: 2
    depends_on:
      rabbitmq:
        condition: service_healthy
  credits_joiner_2:
    image: movies/credits_joiner:latest
    environment:
      ID: 2
      REPLICAS: 2
    depends_on:
      rabbitmq:
        condition: service_healthy
  credits_receiver_1:
    image: movies/credits_receiver:latest
    environment:
      ID: 1
      REPLICAS: 2
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /credits_receiver/credits_receiver.go
  credits_receiver_2:
    image: movies/credits_receiver:latest
    environment:
      ID: 2
      REPLICAS: 2
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /credits_receiver/credits_receiver.go
  credits_sink_1:
    image: movies/sink_q4:latest
    environment:
      ID: 1
      REPLICAS: 1
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /credits_sink/credits_sink.go
  moviesreceiver_resuscitator:
    image: movies/resuscitator:latest
    environment:
      ID: 1
      REPLICAS: 2
      SERVICE_TYPE: moviesreceiver
      PORT: 8000
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yml:/app/docker-compose.yml
    privileged: true
  client:
    image: movies/client:latest
    depends_on:
      - requesthandler
    deploy:
      replicas: 2
    volumes:
      - ./docs:/docs
