name: movies-analysis
services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
    healthcheck:
      test:
        - CMD
        - rabbitmqctl
        - status
      interval: 10s
      timeout: 5s
      retries: 5
  requesthandler:
    environment:
      ID: 1
      REPLICAS: 1
    build:
      context: .
      dockerfile: cmd/requesthandler/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./docs:/docs
    command: /requesthandler/request_handler.go
  moviesreceiver_1:
    environment:
      ID: 1
      REPLICAS: 2
    build:
      context: .
      dockerfile: cmd/moviesreceiver/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
  moviesreceiver_2:
    environment:
      ID: 2
      REPLICAS: 2
    build:
      context: .
      dockerfile: cmd/moviesreceiver/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
  filter_q1_1:
    environment:
      QUERY: 1
      ID: 1
      REPLICAS: 2
    build:
      context: .
      dockerfile: cmd/filter/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /filter/filter.go
  filter_q1_2:
    environment:
      QUERY: 1
      ID: 2
      REPLICAS: 2
    build:
      context: .
      dockerfile: cmd/filter/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /filter/filter.go
  # filter_q3_1:
  #   environment:
  #     QUERY: 3
  #     ID: 1
  #     REPLICAS: 2
  #   build:
  #     context: .
  #     dockerfile: cmd/filter/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   command: /filter/filter.go
  # filter_q3_2:
  #   environment:
  #     QUERY: 3
  #     ID: 2
  #     REPLICAS: 2
  #   build:
  #     context: .
  #     dockerfile: cmd/filter/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   command: /filter/filter.go
  # filter_q4_1:
  #   environment:
  #     QUERY: 4
  #     ID: 1
  #     REPLICAS: 2
  #   build:
  #     context: .
  #     dockerfile: cmd/filter/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   command: /filter/filter.go
  # filter_q4_2:
  #   environment:
  #     QUERY: 4
  #     ID: 2
  #     REPLICAS: 2
  #   build:
  #     context: .
  #     dockerfile: cmd/filter/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   command: /filter/filter.go
  # ratingsreceiver_1:
  #   environment:
  #     ID: 1
  #     REPLICAS: 2
  #   build:
  #     context: .
  #     dockerfile: cmd/ratingsreceiver/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # ratingsreceiver_2:
  #   environment:
  #     ID: 2
  #     REPLICAS: 2
  #   build:
  #     context: .
  #     dockerfile: cmd/ratingsreceiver/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # ratingsjoiner_1:
  #   environment:
  #     ID: 1
  #     REPLICAS: 2
  #   build:
  #     context: .
  #     dockerfile: cmd/joiners/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # ratingsjoiner_2:
  #   environment:
  #     ID: 2
  #     REPLICAS: 2
  #   build:
  #     context: .
  #     dockerfile: cmd/joiners/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  q1_sink_1:
    environment:
      ID: 1
      REPLICAS: 1
    build:
      context: .
      dockerfile: cmd/sinks/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: /q1_sink/q1_sink.go
  # q3_sink_1:
  #   environment:
  #     ID: 1
  #     REPLICAS: 1
  #   build:
  #     context: .
  #     dockerfile: cmd/sinks_q3/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # budget_reducer_1:
  #   environment:
  #     ID: 1
  #     REPLICAS: 2
  #   build:
  #     context: .
  #     dockerfile: cmd/reducers/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   command: /budget_reducer.go
  # budget_reducer_2:
  #   environment:
  #     ID: 2
  #     REPLICAS: 2
  #   build:
  #     context: .
  #     dockerfile: cmd/reducers/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   command: /budget_reducer.go
  # budget_sink_1:
  #   environment:
  #     ID: 1
  #     REPLICAS: 1
  #   build:
  #     context: .
  #     dockerfile: cmd/sinks_q2/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   command: /budget_sink/budget_sink.go
  # sentiment_worker_1:
  #   environment:
  #     ID: 1
  #     REPLICAS: 3
  #   build:
  #     context: .
  #     dockerfile: cmd/sentiment/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # sentiment_worker_2:
  #   environment:
  #     ID: 2
  #     REPLICAS: 3
  #   build:
  #     context: .
  #     dockerfile: cmd/sentiment/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # sentiment_worker_3:
  #   environment:
  #     ID: 3
  #     REPLICAS: 3
  #   build:
  #     context: .
  #     dockerfile: cmd/sentiment/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # sentiment_reducer_1:
  #   environment:
  #     ID: 1
  #     REPLICAS: 2
  #   build:
  #     context: .
  #     dockerfile: cmd/reducers/sentiment_reducer/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   command: /sentiment_reducer/sentiment_reducer.go
  # sentiment_reducer_2:
  #   environment:
  #     ID: 2
  #     REPLICAS: 2
  #   build:
  #     context: .
  #     dockerfile: cmd/reducers/sentiment_reducer/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   command: /sentiment_reducer/sentiment_reducer.go
  # credits_joiner_1:
  #   environment:
  #     ID: 1
  #     REPLICAS: 2
  #   build:
  #     context: .
  #     dockerfile: cmd/joiners_q4/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # credits_joiner_2:
  #   environment:
  #     ID: 2
  #     REPLICAS: 2
  #   build:
  #     context: .
  #     dockerfile: cmd/joiners_q4/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # credits_receiver_1:
  #   environment:
  #     ID: 1
  #     REPLICAS: 2
  #   build:
  #     context: .
  #     dockerfile: cmd/credits_receiver/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   command: /credits_receiver/credits_receiver.go
  # credits_receiver_2:
  #   environment:
  #     ID: 2
  #     REPLICAS: 2
  #   build:
  #     context: .
  #     dockerfile: cmd/credits_receiver/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   command: /credits_receiver/credits_receiver.go
  # credits_sink_1:
  #   environment:
  #     ID: 1
  #     REPLICAS: 1
  #   build:
  #     context: .
  #     dockerfile: cmd/sinks_q4/Dockerfile
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   command: /credits_sink/credits_sink.go
  client:
    build:
      context: .
      dockerfile: cmd/client/Dockerfile
    depends_on:
      - requesthandler
    deploy:
      replicas: 2
    volumes:
      - ./docs:/docs
