name: movies-analysis
services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
    healthcheck:
      test:
        - CMD
        - rabbitmqctl
        - status
      interval: 10s
      timeout: 5s
      retries: 5
  requesthandler:
    environment:
      ID: 1
      REPLICAS: 1
      SERVICE_TYPE: requesthandler
    image: movies/requesthandler:latest
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./docs:/docs
      - requesthandler_volume:/data
    command: /requesthandler/request_handler.go
  moviesreceiver_1:
    container_name: moviesreceiver_1
    image: movies/moviesreceiver:latest
    environment:
      ID: 1
      REPLICAS: 2
      SERVICE_TYPE: moviesreceiver
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - moviesreceiver_1_volume:/data
  moviesreceiver_2:
    container_name: moviesreceiver_2
    image: movies/moviesreceiver:latest
    environment:
      ID: 2
      REPLICAS: 2
      SERVICE_TYPE: moviesreceiver
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - moviesreceiver_2_volume:/data
  filter_q1_1:
    container_name: filter_q1_1
    image: movies/filter:latest
    environment:
      ID: 1
      REPLICAS: 2
      SERVICE_TYPE: filter_q1
      QUERY: 1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - filter_q1_1_volume:/data
    command: /filter/filter.go
  filter_q1_2:
    container_name: filter_q1_2
    image: movies/filter:latest
    environment:
      ID: 2
      REPLICAS: 2
      SERVICE_TYPE: filter_q1
      QUERY: 1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - filter_q1_2_volume:/data
    command: /filter/filter.go
  filter_q3_1:
    container_name: filter_q3_1
    image: movies/filter:latest
    environment:
      ID: 1
      REPLICAS: 2
      SERVICE_TYPE: filter_q3
      QUERY: 3
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - filter_q3_1_volume:/data
    command: /filter/filter.go
  filter_q3_2:
    container_name: filter_q3_2
    image: movies/filter:latest
    environment:
      ID: 2
      REPLICAS: 2
      SERVICE_TYPE: filter_q3
      QUERY: 3
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - filter_q3_2_volume:/data
    command: /filter/filter.go
  filter_q4_1:
    container_name: filter_q4_1
    image: movies/filter:latest
    environment:
      ID: 1
      REPLICAS: 2
      SERVICE_TYPE: filter_q4
      QUERY: 4
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - filter_q4_1_volume:/data
    command: /filter/filter.go
  filter_q4_2:
    container_name: filter_q4_2
    image: movies/filter:latest
    environment:
      ID: 2
      REPLICAS: 2
      SERVICE_TYPE: filter_q4
      QUERY: 4
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - filter_q4_2_volume:/data
    command: /filter/filter.go
  ratingsreceiver_1:
    container_name: ratingsreceiver_1
    image: movies/ratingsreceiver:latest
    environment:
      ID: 1
      REPLICAS: 2
      SERVICE_TYPE: ratingsreceiver
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ratingsreceiver_1_volume:/data
  ratingsreceiver_2:
    container_name: ratingsreceiver_2
    image: movies/ratingsreceiver:latest
    environment:
      ID: 2
      REPLICAS: 2
      SERVICE_TYPE: ratingsreceiver
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ratingsreceiver_2_volume:/data
  ratingsjoiner_1:
    container_name: ratingsjoiner_1
    image: movies/ratingsjoiner:latest
    environment:
      ID: 1
      REPLICAS: 2
      SERVICE_TYPE: ratingsjoiner
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ratingsjoiner_1_volume:/data
  ratingsjoiner_2:
    container_name: ratingsjoiner_2
    image: movies/ratingsjoiner:latest
    environment:
      ID: 2
      REPLICAS: 2
      SERVICE_TYPE: ratingsjoiner
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ratingsjoiner_2_volume:/data
  q1_sink_1:
    container_name: q1_sink_1
    image: movies/sink:latest
    environment:
      ID: 1
      REPLICAS: 1
      SERVICE_TYPE: q1_sink
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - q1_sink_1_volume:/data
    command: /q1_sink/q1_sink.go
  q3_sink_1:
    container_name: q3_sink_1
    image: movies/sink_q3:latest
    environment:
      ID: 1
      REPLICAS: 1
      SERVICE_TYPE: q3_sink
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - q3_sink_1_volume:/data
  budget_reducer_1:
    container_name: budget_reducer_1
    image: movies/reducer:latest
    environment:
      ID: 1
      REPLICAS: 2
      SERVICE_TYPE: budget_reducer
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - budget_reducer_1_volume:/data
    command: /budget_reducer.go
  budget_reducer_2:
    container_name: budget_reducer_2
    image: movies/reducer:latest
    environment:
      ID: 2
      REPLICAS: 2
      SERVICE_TYPE: budget_reducer
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - budget_reducer_2_volume:/data
    command: /budget_reducer.go
  budget_sink_1:
    container_name: budget_sink_1
    image: movies/sink_q2:latest
    environment:
      ID: 1
      REPLICAS: 1
      SERVICE_TYPE: budget_sink
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - budget_sink_1_volume:/data
    command: /budget_sink/budget_sink.go
  sentiment_worker_1:
    container_name: sentiment_worker_1
    image: movies/sentiment:latest
    environment:
      ID: 1
      REPLICAS: 2
      SERVICE_TYPE: sentiment_worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - sentiment_worker_1_volume:/data
    command: /sentiment/sentiment_worker.go
  sentiment_worker_2:
    container_name: sentiment_worker_2
    image: movies/sentiment:latest
    environment:
      ID: 2
      REPLICAS: 2
      SERVICE_TYPE: sentiment_worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - sentiment_worker_2_volume:/data
    command: /sentiment/sentiment_worker.go
  sentiment_reducer_1:
    container_name: sentiment_reducer_1
    image: movies/sentiment_reducer:latest
    environment:
      ID: 1
      REPLICAS: 1
      SERVICE_TYPE: sentiment_reducer
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - sentiment_reducer_1_volume:/data
    command: /sentiment_reducer/sentiment_reducer.go
  sentiment_sink_1:
    container_name: sentiment_sink_1
    image: movies/sink_q5:latest
    environment:
      ID: 1
      REPLICAS: 1
      SERVICE_TYPE: sentiment_sink
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - sentiment_sink_1_volume:/data
    command: /sentiment_sink/sentiment_sink.go
  credits_joiner_1:
    container_name: credits_joiner_1
    image: movies/credits_joiner:latest
    environment:
      ID: 1
      REPLICAS: 2
      SERVICE_TYPE: credits_joiner
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - credits_joiner_1_volume:/data
  credits_joiner_2:
    container_name: credits_joiner_2
    image: movies/credits_joiner:latest
    environment:
      ID: 2
      REPLICAS: 2
      SERVICE_TYPE: credits_joiner
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - credits_joiner_2_volume:/data
  credits_receiver_1:
    container_name: credits_receiver_1
    image: movies/credits_receiver:latest
    environment:
      ID: 1
      REPLICAS: 2
      SERVICE_TYPE: credits_receiver
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - credits_receiver_1_volume:/data
    command: /credits_receiver/credits_receiver.go
  credits_receiver_2:
    container_name: credits_receiver_2
    image: movies/credits_receiver:latest
    environment:
      ID: 2
      REPLICAS: 2
      SERVICE_TYPE: credits_receiver
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - credits_receiver_2_volume:/data
    command: /credits_receiver/credits_receiver.go
  credits_sink_1:
    container_name: credits_sink_1
    image: movies/sink_q4:latest
    environment:
      ID: 1
      REPLICAS: 1
      SERVICE_TYPE: credits_sink
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - credits_sink_1_volume:/data
    command: /credits_sink/credits_sink.go
  resuscitator_1:
    container_name: resuscitator_1
    image: movies/resuscitator:latest
    environment:
      ID: 1
      REPLICAS: 3
      SERVICE_TYPE: resuscitator
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yml:/app/docker-compose.yml
  resuscitator_2:
    container_name: resuscitator_2
    image: movies/resuscitator:latest
    environment:
      ID: 2
      REPLICAS: 3
      SERVICE_TYPE: resuscitator
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yml:/app/docker-compose.yml
  resuscitator_3:
    container_name: resuscitator_3
    image: movies/resuscitator:latest
    environment:
      ID: 3
      REPLICAS: 3
      SERVICE_TYPE: resuscitator
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yml:/app/docker-compose.yml
  client:
    image: movies/client:latest
    depends_on:
      - requesthandler
    deploy:
      replicas: 2
    volumes:
      - ./docs:/docs
  chaosmonkey:
    image: movies/chaosmonkey:latest
    environment:
      ID: 1
      MIN_INTERVAL_SECONDS: 5
      MAX_INTERVAL_SECONDS: 8
      KILL_PROBABILITY: 0.4
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yml:/app/docker-compose.yml
    privileged: true
volumes:
  rabbitmq_volume: {}
  requesthandler_volume: {}
  moviesreceiver_1_volume: {}
  moviesreceiver_2_volume: {}
  filter_q1_1_volume: {}
  filter_q1_2_volume: {}
  filter_q3_1_volume: {}
  filter_q3_2_volume: {}
  filter_q4_1_volume: {}
  filter_q4_2_volume: {}
  ratingsreceiver_1_volume: {}
  ratingsreceiver_2_volume: {}
  ratingsjoiner_1_volume: {}
  ratingsjoiner_2_volume: {}
  q1_sink_1_volume: {}
  q3_sink_1_volume: {}
  budget_reducer_1_volume: {}
  budget_reducer_2_volume: {}
  budget_sink_1_volume: {}
  sentiment_worker_1_volume: {}
  sentiment_worker_2_volume: {}
  sentiment_reducer_1_volume: {}
  sentiment_sink_1_volume: {}
  credits_joiner_1_volume: {}
  credits_joiner_2_volume: {}
  credits_receiver_1_volume: {}
  credits_receiver_2_volume: {}
  credits_sink_1_volume: {}
